onflow/vscode-cadence

package.json

Add an option that traces the communication between the language server and the language client.
It is turned off by default. This helps with the development / debugging of the extension and the Cadence language server.
This is just adding a UI option in the settings. The actual functionality is provided by `vscode-languageclient`. See https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#logging-support-for-language-server

Add a tracing option

---

src/commands.ts
src/config.ts
src/extension.ts
src/status-bar.ts

- Remove service account entirely from extension state
- Set `activeAccount = null` if no accounts created yet
- Once emulator is started and first account exists, set it as active 
- Once at least one account exists, display account switcher
- Add Start/Stop button for emulator

Remove service account, hide account switcher until emulator is running

---

package.json

Ensure the extension is started whenever any of the commands is invoked.
Unfortunately it doesn't seem possible to use a wildcard yet: https://github.com/microsoft/vscode/issues/16045

Add all commands to list of activation events

---

README.md

Closes #36
I moved the developer documentation to https://github.com/onflow/vscode-flow/blob/master/docs/development.md
______

Fix installation instructions for CLI

---

src/config.ts
src/extension.ts

The extension and language server now require a Flow CLI config.
If none exits, there is currently only a cryptic "invalid language server initialization options" error.
Prompt the user if they would like to create a new config if it is missing, and run `flow init` if they agree.
______

Prompt for running flow init to create a CLI config

---

.vscodeignore
package-lock.json
package.json

Packaging was reporting:
```
This extension consists of 2476 files, out of which 2086 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
```
I followed the instruction and added esbuild. It's very fast, generates a single small file, and works like a charm:
```
out/main.js  271.3kb
⚡ Done in 35ms
```
______

Use esbuild to bundle

---

src/commands.ts

Closes #60 
- Updates the emulator start command to move away from the deprecated `flow project` version
- Fixes the issue where the emulator fails to start if the project path contains spaces
______

Update emulator start command

---

extension/src/commands/command-constants.ts
extension/src/commands/command-controller.ts
extension/src/emulator/emulator-controller.ts
package.json

Closes #22 
Added a command to copy the active account to clipboard.
______

Copy active account to clipboard

---

extension/src/dependency-installer/installers/flow-cli-installer.ts
extension/test/e2e/2-deploy-contract.test.ts
extension/test/e2e/4-send-transaction.test.ts
extension/test/e2e/cypress-helpers.ts
package.json

Closes #156 
- Updated e2e-tests to reflect new output strings from LS
______

Update e2e tests for v1.0.0 release

---

extension/src/telemetry/sentry-wrapper.ts

Closes #160 
Added an ignore list to sentry initialization in order to ignore:
- Syntax Errors from the language server
- No valid config path error caused by no flow.json file
______

Ignore syntax errors in Sentry

---

package.json

Closes #210 
Release v1.0.6
______

Bump release to v1.0.6

---

package-lock.json
package.json

Update to the latest release of vscode-languageclient, which includes https://github.com/microsoft/vscode-languageserver-node/commit/529ee895d84a04723b11743ec5c568a9347c3d97 which fixes
https://github.com/microsoft/vscode-languageserver-node/issues/968:
`completion` requests were sometimes sent before `didChange` requests, leading to broken/flaky completions
Also, 184f9df8b36c7a3632041411ec07480f4ce7fca8 seems to have accidentally added a dependency `-`. Remove it
______

Update language client

---

extension/src/emulator/server/language-server.ts
package-lock.json
package.json

Closes #215 
Added a delay on restarting the language server to enable flow.exe to be updated on Windows when the running flow.exe process is killed.
______

Enable LS to wait for flow-cli update

---

extension/src/emulator/server/language-server.ts

Closes #234 
Adds missing configuration value to initialization for accessCheckMode.
______

Add missing configuration for access check mode

---

extension/src/emulator/local/config.ts
extension/src/emulator/server/language-server.ts
extension/src/extension.ts

Closes https://github.com/onflow/cadence-tools/issues/57
Reload configuration when changed so the LS can reload.
______

Reload flow configuration when changed

---

extension/src/dependency-installer/installers/flow-cli-installer.ts
package.json

Closes #233 #239 
- Updates flow-cli required minimum version to v0.44.0 to enable LS updates
- Updated extension version to v1.0.7
______

Update required flow-cli version

---

CONTRIBUTING.md

Since the language server has been removed from the [onflow/cadence](https://github.com/onflow/cadence) repository ([this PR](https://github.com/onflow/cadence/commit/525d622acf2b19068373522018bad1ebb5e07e83)), we need to update the link in [CONTRIBUTING.md](https://github.com/onflow/vscode-cadence/blob/7d8a7aa39957d484171cfcb726056fdba94588a8/CONTRIBUTING.md) to the current one.
The language server codebase now exists in [onflow/cadence-tools](https://github.com/onflow/cadence-tools).

Update Cadence language server link

---

extension/src/commands/command-controller.ts
extension/src/emulator/emulator-controller.ts
extension/src/extension.ts
extension/src/telemetry/telemetry.ts
extension/test/integration/3 - commands.test.ts

Closes #340
Made commands in CommandController async so we may wait for their completion/catch errors.  Speeds up tests and removes arbitrary delays.
______

Make commands async so their execution may be awaited

---

extension/src/emulator/emulator-controller.ts
extension/src/emulator/server/language-server.ts

Closes #349 
These errors appearing in CI were actually caused by language server instances leaking between tests.  The objects were not being disposed of correctly, causing them to compete for the emulator connection & other resources.  This explained the proposal key sequence number issues as well.
This PR fixes the deactivation of the LS & ensures that all necessary tasks are properly awaited.  The main culprit here was the emulator watcher loop not being cleaned up properly (timeout was cleared, but the async function had already started).
______

Fix langauge server instance leaking between tests

---

package-lock.json
package.json

We are using functionality from semver but it's not tracked it package.json and instead comes as a dependency of other packages.  This probably should not be done (for version control amongst other reasons) so this PR adds it to the package.json and bumps it to 7.5.1 as we were technically using v6 from @babel/core previously by the looks of it.

Add semver to package.json & bump to 7.5.1

---

extension/test/run-tests.ts

Closes #358 
This disables hardware acceleration in tests which seems to be the likely culprit of the transient failures experienced in Windows.
It kind of appears that this is something fixed in newer versions of electron but until we bump the VSCode engine version, this fix will likely be required.
______

Disable hardware acceleration to fix Windows tests

---

extension/src/json-schema-provider.ts
extension/test/integration/4 - schema.test.ts

Fixes a typo in the flow.json schema URL that was causing the schema to fail to be resolved

Fix schema URL typo

---

extension/src/emulator/local/flowConfig.ts
extension/src/emulator/server/language-server.ts
extension/src/settings/settings.ts

Closes #406 
This fixes the issue at hand.  Now when I delete, create, update, change settings, etc. the correct flow.json is always in use and the emulator connects - there is no longer any issue with the extension breaking.
______

Handle edge cases when watching for flow.json changes

---

extension/src/dependency-installer/installers/flow-cli-installer.ts

Allow pre-release CLI versions

---

extension/src/extension.ts
package-lock.json
package.json

Fixes bug that only exists in production/when extension is packaged.  Node modules don't come with the extension bundle so the WASM file needs to be manually copied to the extension output

Fix Cadence Testing bug when packaged in VSIX

---

extension/src/main.ts
extension/src/server/flow-config.ts
extension/src/server/language-server.ts
extension/src/settings/settings.ts
extension/src/test-provider/test-runner.ts
extension/test/integration/4 - flow-config.test.ts
extension/test/integration/6 - test-provider.test.ts
extension/test/mock/mockSettings.ts
package-lock.json
package.json

Closes #494 
- Some refactoring to the Settings class (it was kind of bloated and all of the stuff for missing values, defaults, etc. is useless since it's handled by VSCode itself).  The singleton was also kind of useless because we were injecting instances everywhere anyways and only complicates testing
- Adds a reload to LS when LS-related configuration changes (important for Cadence 1.0, since users will be changing `cadence.flowCommand` setting)
- Changes test concurrency setting to `test.maxConcurrency` instead.  This was an oversight when I originally added the feature, it probably makes sense to start getting in the habit of namespacing properly.
Imo if specific settings require additional transformations, etc. we can move these to their own sub-providers but the top-level …

Reload the LS when relevant config changes

---

extension/src/flow-cli/cli-provider.ts

Closes #564 
Use new JSON output and fallback to old method
______

Use JSON `flow version` output

---

extension/src/dependency-installer/installers/flow-cli-installer.ts
extension/src/flow-cli/binary-versions-provider.ts
extension/src/flow-cli/cli-provider.ts
extension/src/flow-cli/cli-selection-provider.ts
extension/src/flow-cli/cli-versions-provider.ts
extension/src/server/language-server.ts
extension/test/integration/1 - language-server.test.ts
extension/test/unit/parser.test.ts
package.json

Closes #575 
Closes #583 
The code was maybe a bit cluttered/hard to follow.  This attempts to break the functionality up a bit better (moves caching into its own class).
Few functionality changes also:
- Hoists currently selected binary to top of list when choosing
- `cadence.changeCadenceVersion` command was a bit of a misnomer which came from the initial vision of this feature (but has deviated since).  This was changed to `cadence.changeFlowCliBinary`
- Also fixes a bug where the CLI version selection would break if an invalid flow command was configured at startup.
- Fixes "bug" when not in workspace folder
______

Refactor CLI version selection

---

extension/src/dependency-installer/installers/flow-cli-installer.ts

Closes #599 
Switch away with soon to be deprecated `version.txt`
______

Use Homebrew to check for latest Flow CLI version

---

package-lock.json
package.json

Closes #634 
Downgrade version of `os-name` package to avoid fatal crash on Windows described in #634.
______

Upgrade `os-name` to avoid crash on Windows
