.vscode/launch.json
package-lock.json
package.json
src/commands.ts
src/config.ts

Closes #5 
- Hides service account address from the UI
- Selects the first default account, once accounts have been bootstrapped after emulator start

Prevent selecting service account in the extension.

---

src/commands.ts

This PR updates the language server command names to match the updated names on the server.

Update language server commands

---

CODEOWNERS
extension/src/emulator/emulator-controller.ts
extension/src/emulator/local/config.ts
extension/src/emulator/tools/terminal.ts
extension/src/settings/settings.ts
package.json

Closes #90 
Added settings to allow users to enable a custom path to their flow.json file.
______

Add settings to support custom flow.json path

---

extension/src/telemetry/mixpanel-wrapper.ts
extension/src/telemetry/sentry-wrapper.ts
extension/src/telemetry/telemetry.ts
package-lock.json
package.json

Closes #145
Added Mixpanel for activation analytics to track the following:
- vscode-cadence version number
- User ID and region
- Operating system name
______

Mixpanel analytics

---

extension/src/dependency-installer/installers/flow-cli-installer.ts
extension/src/extension.ts
extension/src/telemetry/mixpanel-wrapper.ts
extension/src/telemetry/telemetry.ts
extension/test/fixtures/workspace/FooContract.cdc
package-lock.json
package.json

Release v1.0.0 improvements

---

extension/src/telemetry/ignore-errors.ts
extension/src/telemetry/mixpanel-wrapper.ts
extension/src/telemetry/sentry-wrapper.ts
extension/src/telemetry/telemetry.ts
package.json

Closes #162
Added all error types to Mixpanel for unhandled exception analytics.
______

Add all errors to mixpanel

---

.github/workflows/release.yml
package-lock.json
package.json

Closes #171 
Create actions to publish to open-vsx
______

Create workflow to publish extension to marketplace and open-vsx

---

package.json

Organize dev dependencies
______

Clean up dev dependencies

---

extension/src/dependency-installer/installers/flow-cli-installer.ts

Update flow-cli dependency to v0.40.0
______

Flow-cli dependency v0.40.0

---

extension/test/e2e/1-switch-accounts.test.ts

Closes #193 
- Updated switch accounts by name test
______

Fix switch account e2e test

---

.github/workflows/release.yml
package-lock.json
package.json

Closes #195 
Update the publish workflow and setup for release of v1.0.5
______

Update publish workflow for v1.0.5

---

extension/src/dependency-installer/installers/flow-cli-installer.ts

Closes #204 
Update to latest flow-cli/ language server to fix codelens on Windows 
______

Update required Flow CLI version to v0.43.1

---

extension/src/dependency-installer/installer.ts
extension/src/dependency-installer/installers/flow-cli-installer.ts
extension/src/telemetry/mixpanel-wrapper.ts
package-lock.json
package.json
tsconfig.json

Closes #206 
Added more thorough popups which guide the user through dependency installations
______

Add installer popups

---

extension/src/dependency-installer/installers/flow-cli-installer.ts

Closes #212 
Update to latest installer scripts
______

Update flow cli install scripts

---

extension/src/dependency-installer/installers/flow-cli-installer.ts
extension/src/dependency-installer/installers/version-parsers.ts
package-lock.json
package.json

Closes #208 
The flow-cli installer will now prompt users to install the latest version if a newer version than their current flow-cli is available.
______

Check for latest flow-cli version

---

.github/workflows/ci.yml
README.md
extension/index.d.ts
extension/src/dependency-installer/dependency-installer.ts
extension/src/emulator/emulator-controller.ts
extension/src/emulator/server/language-server.ts
extension/test/e2e/0-init.test.ts
extension/test/e2e/1-switch-accounts.test.ts
extension/test/e2e/2-deploy-contract.test.ts
extension/test/e2e/3-send-script.test.ts
extension/test/e2e/4-send-transaction.test.ts
extension/test/e2e/cypress-helpers.ts
extension/test/fixtures/workspace/NonFungibleToken.cdc
package-lock.json
package.json

Closes #242 
The extension will now scan for a local emulator to connect to, and will no longer host its own emulator.
______

Refactor emulator integration

---

extension/src/dependency-installer/installers/flow-cli-installer.ts
package.json

Closes #245 
- Prepare v1.1.0 release
- Update required flow-cli to v0.45.0
______

Update version to v1.1.0

---

README.md
compile-install.sh
extension/src/dependency-installer/installers/flow-cli-installer.ts
package-lock.json
package.json

Closes #264 
Prepare for release of v1.2.0
- Updates minimum required flow-cli version
- Added debugging to README
______

Release v1.2.0

---

.github/workflows/ci.yml
extension/src/dependency-installer/installers/flow-cli-installer.ts

Closes #326 
Adds github token to flow CLI installation to prevent rate limiting by the API
______

Add GitHub token to Flow CLI installation

---

extension/src/emulator/emulator-controller.ts
extension/src/emulator/local/flowConfig.ts
extension/src/emulator/server/language-server.ts
extension/test/unit/flowConfig.test.ts

Closes #314 
This PR fixes listening for flow.json changes as they were not being recognized properly prior.
______

Fix flow.json change listener

---

extension/src/dependency-installer/installers/flow-cli-installer.ts

Closes #345 
I put a bracket in the wrong place :)
______

Fix Windows install Flow CLI GH token

---

extension/src/dependency-installer/installers/flow-cli-installer.ts
extension/src/extension.ts
extension/src/json-schema-provider.ts
extension/src/utils/flow-version.ts
extension/src/utils/state-cache.ts
extension/test/integration/4 - schema.test.ts
extension/test/unit/parser.test.ts
flow-schema.json
package.json

Include flow.json schema for suggestions and validation

---

CODEOWNERS

Closes #450
updating code owners
______

trim code owners

---

package.json

Need to release new version to fix sentry bug

Bump package.json to 1.4.1

---

package-lock.json
package.json

Bump package.json version for release

Bump to v2.3.0

---

extension/src/crypto-polyfill.ts

Closes #626 
Fixes crypto polyfill broken by v1.90.0
______

Fix crypto polyfill
